"""Run YOLO-seg prediction and save visualized results.

Prerequisites:
    Install Ultralytics inside the dev container:
        make shell
        pip install ultralytics

Usage:
    python examples/vision_baseline/03_predict_yolo.py

    python examples/vision_baseline/03_predict_yolo.py \
      --source playground/Datasets/g1_sorttoshelf_pick_v0/front_head_rgb_camera/images/val

    python examples/vision_baseline/03_predict_yolo.py \
      --model playground/Checkpoints/g1_sorttoshelf_pick_v0_front_head_rgb_camera/weights/best.pt \
      --source path/to/image_or_directory

By default, the only best.pt under playground/Checkpoints is used and prediction
visualizations are written to playground/Predictions/. If --source is omitted,
the default SortToShelf validation image directory is used.

See docs/yolo_seg.md for the full workflow.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

# Two levels up from examples/vision_baseline/ to the repo root.
REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_CHECKPOINT_ROOT = "playground/Checkpoints"
DEFAULT_OUTPUT_ROOT = "playground/Predictions"
DEFAULT_SOURCE = (
    "playground/Datasets/g1_sorttoshelf_pick_v0/front_head_rgb_camera/images/val"
)
DEFAULT_IMAGE_SIZE = 320
DEFAULT_CONFIDENCE = 0.25
DEFAULT_IOU = 0.7


def main(argv: list[str] | None = None) -> None:
    """Command-line entry point."""

    args = parse_args(argv)
    model_path = resolve_model_path(
        model=args.model, checkpoint_root=DEFAULT_CHECKPOINT_ROOT
    )
    source_path = resolve_source_path(args.source)
    output_root = resolve_repo_path(DEFAULT_OUTPUT_ROOT)

    YOLO = import_yolo()
    model = YOLO(str(model_path))
    results = model.predict(
        source=str(source_path),
        project=str(output_root),
        name=args.name,
        exist_ok=args.exist_ok,
        imgsz=args.imgsz,
        conf=DEFAULT_CONFIDENCE,
        iou=DEFAULT_IOU,
        classes=parse_class_ids(args.classes),
        visualize=False,
        save=True,
        show=False,
        task="segment",
    )
    save_dir = prediction_save_dir(results)
    print(f"[predict] Model: {model_path}")
    print(f"[predict] Source: {source_path}")
    if save_dir is not None:
        print(f"[predict] Visualizations saved to: {save_dir}")


def parse_args(argv: list[str] | None) -> argparse.Namespace:
    """Parse CLI arguments."""

    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--source",
        default=DEFAULT_SOURCE,
        help=(
            "Image file, video file, or directory to predict. Defaults to the "
            "SortToShelf validation image directory generated by example 15."
        ),
    )
    parser.add_argument(
        "--model",
        default=None,
        help=(
            "Path to a trained .pt checkpoint. If omitted, playground/Checkpoints "
            "must contain exactly one weights/best.pt."
        ),
    )
    parser.add_argument(
        "--name",
        default="predict",
        help="Prediction run name under playground/Predictions.",
    )
    parser.add_argument(
        "--classes",
        default=None,
        help=(
            "Optional comma-separated YOLO class ids to predict, e.g. 0,2. "
            "Defaults to all classes."
        ),
    )
    parser.add_argument(
        "--imgsz",
        type=int,
        default=DEFAULT_IMAGE_SIZE,
        help=f"Ultralytics prediction input size. Defaults to {DEFAULT_IMAGE_SIZE}.",
    )
    parser.add_argument("--exist-ok", action="store_true")
    args = parser.parse_args(argv)
    if args.imgsz < 1:
        raise ValueError("--imgsz must be greater than zero.")
    return args


def import_yolo() -> Any:
    """Import Ultralytics with a clear setup error."""

    try:
        from ultralytics import YOLO
    except ModuleNotFoundError as exc:
        raise ModuleNotFoundError(
            "ultralytics is required for YOLO prediction but is not included in "
            "the default ioailab Docker image. Install it inside the dev "
            "container with `pip install ultralytics`, then rerun this command."
        ) from exc
    return YOLO


def resolve_repo_path(path: str) -> Path:
    """Resolve a path relative to the repository root when needed."""

    candidate = Path(path).expanduser()
    if candidate.is_absolute():
        return candidate.resolve()
    return (REPO_ROOT / candidate).resolve()


def resolve_model_path(*, model: str | None, checkpoint_root: str) -> Path:
    """Return the requested or unique trained checkpoint."""

    if model:
        path = resolve_repo_path(model)
        if not path.is_file():
            raise FileNotFoundError(f"Model checkpoint does not exist: {path}")
        return path

    root = resolve_repo_path(checkpoint_root)
    candidates = sorted(
        path for path in root.rglob("weights/best.pt") if path.is_file()
    )
    if not candidates:
        raise FileNotFoundError(
            f"No weights/best.pt found under {root}. Train a model first with "
            "`python examples/vision_baseline/02_train_yolo.py ...` or pass --model."
        )
    if len(candidates) > 1:
        formatted = "\n".join(f"  - {path}" for path in candidates)
        raise ValueError(
            f"Multiple weights/best.pt files found under {root}. Pass --model explicitly.\n"
            f"{formatted}"
        )
    return candidates[0]


def resolve_source_path(source: str) -> Path:
    """Resolve and validate the prediction source path."""

    path = resolve_repo_path(source)
    if not path.exists():
        raise FileNotFoundError(
            f"Prediction source does not exist: {path}. Generate it first with "
            "`python examples/vision_baseline/01_generate_yolo_dataset.py --headless` "
            "or pass --source."
        )
    return path


def prediction_save_dir(results: Any) -> Path | None:
    """Return the Ultralytics prediction save directory when available."""

    if not results:
        return None
    first = results[0]
    save_dir = getattr(first, "save_dir", None)
    return Path(save_dir) if save_dir is not None else None


def parse_class_ids(value: str | None) -> list[int] | None:
    """Parse comma-separated YOLO class ids for Ultralytics prediction."""

    if value is None or not value.strip():
        return None
    class_ids: list[int] = []
    for raw_part in value.split(","):
        part = raw_part.strip()
        if not part:
            continue
        class_id = int(part)
        if class_id < 0:
            raise ValueError("--classes must contain non-negative class ids.")
        class_ids.append(class_id)
    return class_ids or None


if __name__ == "__main__":
    main()
