"""Helpers for composing coherent tasks from standalone phase tasks."""

from __future__ import annotations

from collections.abc import Callable, Iterable, Mapping, Sequence
from dataclasses import dataclass
import sys
from typing import Any

import isaaclab.envs.mdp as base_mdp
from isaaclab.managers import EventTermCfg as EventTerm
from isaaclab.managers import ObservationGroupCfg as ObsGroup
from isaaclab.managers import TerminationTermCfg as DoneTerm
from isaaclab.utils.configclass import configclass

from ioailab.agents.flow import AgentProvider, TaskFlowSpec, TaskPhaseSpec
import ioailab.envs.flow as env_flow
from ioailab.tasks import TaskSpec, motion_plan_for_task, nav_agent_for_task


@dataclass(frozen=True, slots=True)
class PhaseTask:
    """Explicit override metadata for one phase task."""

    name: str
    task_id: str
    action_terms: tuple[str, ...] | None = None
    agent: AgentProvider | None = None
    fixed_base: bool = False


@dataclass(frozen=True, slots=True)
class CombinedTaskDefinition:
    """Generated coherent-task metadata and cfg classes."""

    task_spec: TaskSpec
    task_flow: TaskFlowSpec
    env_cfg_cls: type
    mdp_cfg_cls: type
    actions_cfg_cls: type
    terminations_cfg_cls: type


def phase(
    name: str,
    task_id: str,
    *,
    action_terms: Sequence[str] | None = None,
    agent: AgentProvider | None = None,
    fixed_base: bool = False,
) -> PhaseTask:
    """Declare one phase task with optional inference overrides."""

    return PhaseTask(
        name=str(name),
        task_id=str(task_id),
        action_terms=None if action_terms is None else tuple(action_terms),
        agent=agent,
        fixed_base=bool(fixed_base),
    )


def task_sequence(*phases: str | PhaseTask) -> tuple[str | PhaseTask, ...]:
    """Return ordered phase declarations for combined-task authoring."""

    if not phases:
        raise ValueError("task_sequence(...) requires at least one phase.")
    return tuple(phases)


def combined_task(
    *,
    name: str,
    task_id: str,
    phases: Sequence[str | PhaseTask],
    module: str | None = None,
    env_cfg_entry_point: str | None = None,
    task_flow_entry_point: str | None = None,
    entry_point: str = "isaaclab.envs:ManagerBasedRLEnv",
    actions_override: type | None = None,
    observation_override: type | None = None,
    events_override: type | None = None,
    rewards_override: type | None = None,
    scene_override: Any | None = None,
    env_attrs: Mapping[str, Any] | None = None,
    requires_cameras: bool = False,
    reset_randomization_events: Sequence[str] = (),
) -> type:
    """Generate a normal IsaacLab EnvCfg from standalone component tasks.

    This is the high-level task-authoring API: users select ordered component
    task IDs, and ioailab generates the EnvCfg/MDP classes that IsaacLab
    needs to construct a coherent full task.
    """

    module_name = module or _caller_module_name()
    class_name = str(name)
    definition = combine_tasks(
        task_id=task_id,
        phases=phases,
        env_cfg_entry_point=env_cfg_entry_point or f"{module_name}:{class_name}",
        task_flow_entry_point=task_flow_entry_point
        or f"{module_name}:{class_name}.task_flow",
        entry_point=entry_point,
        env_cfg_cls_name=class_name,
        mdp_cfg_cls_name=f"{class_name.removesuffix('EnvCfg')}MdpCfg",
        actions_cfg_cls_name=f"{class_name.removesuffix('EnvCfg')}ActionsCfg",
        terminations_cfg_cls_name=(
            f"{class_name.removesuffix('EnvCfg')}TerminationsCfg"
        ),
        events_cfg_cls_name=f"{class_name.removesuffix('EnvCfg')}EventsCfg",
        observations_cfg_cls_name=f"{class_name.removesuffix('EnvCfg')}ObservationsCfg",
        module=module_name,
        env_cfg_module=module_name,
        actions_override=actions_override,
        observation_override=observation_override,
        events_override=events_override,
        rewards_override=rewards_override,
        scene_override=scene_override,
        env_attrs=env_attrs,
        requires_cameras=requires_cameras,
        reset_randomization_events=reset_randomization_events,
    )
    return definition.env_cfg_cls


def combined_task_definition(env_cfg_cls: type) -> CombinedTaskDefinition:
    """Return generated metadata for a class from :func:`combined_task`.

    The metadata is intentionally stored on an underscored class attribute so
    IsaacLab's config traversal does not walk back into the generated EnvCfg.
    """

    definition = getattr(env_cfg_cls, "_combined_task_definition", None)
    if not isinstance(definition, CombinedTaskDefinition):
        raise ValueError(
            f"{env_cfg_cls!r} was not generated by "
            "ioailab.tasks.common.composition.combined_task."
        )
    return definition


def combine_tasks(
    *,
    task_id: str,
    phases: Sequence[str | PhaseTask],
    env_cfg_entry_point: str,
    env_cfg_cls_name: str,
    mdp_cfg_cls_name: str,
    actions_cfg_cls_name: str,
    terminations_cfg_cls_name: str,
    events_cfg_cls_name: str | None = None,
    observations_cfg_cls_name: str | None = None,
    module: str,
    env_cfg_module: str | None = None,
    task_flow_entry_point: str | None = None,
    entry_point: str = "isaaclab.envs:ManagerBasedRLEnv",
    actions_override: type | None = None,
    observation_override: type | None = None,
    events_override: type | None = None,
    rewards_override: type | None = None,
    scene_override: Any | None = None,
    env_attrs: Mapping[str, Any] | None = None,
    requires_cameras: bool = False,
    reset_randomization_events: Sequence[str] = (),
    phase_state_getter: str = "current_task_phases",
) -> CombinedTaskDefinition:
    """Compose a coherent task from ordered standalone phase task IDs.

    The composer treats each phase EnvCfg's ``evaluation_success`` as that
    phase's success predicate. Non-final successes become phase transitions;
    final success becomes coherent-task success. Timeout remains a coherent
    task timeout.
    """

    specs = tuple(_resolve_phase_task(item) for item in phases)
    if not specs:
        raise ValueError("combine_tasks(...) requires at least one phase.")

    phase_cfgs = tuple(_phase_env_cfg(spec.task_id) for spec in specs)
    flow = _make_task_flow(specs, phase_cfgs, phase_state_getter)
    actions_cls = actions_override or _make_actions_cfg(
        actions_cfg_cls_name, module, phase_cfgs
    )
    final_success = _success_term(phase_cfgs[-1], specs[-1].task_id)
    terminations_cls = _make_terminations_cfg(
        terminations_cfg_cls_name,
        module,
        specs=specs,
        phase_cfgs=phase_cfgs,
        final_success=final_success,
    )
    observations_cls = observation_override or _make_observations_cfg(
        observations_cfg_cls_name or f"{mdp_cfg_cls_name}Observations",
        module,
        phase_cfgs,
    )
    events_cls = _make_events_cfg(
        events_cfg_cls_name or f"{mdp_cfg_cls_name}Events",
        module,
        events_override or type(phase_cfgs[0].events),
    )
    rewards_cls = rewards_override or type(phase_cfgs[0].rewards)
    mdp_cls = _make_mdp_cfg(
        mdp_cfg_cls_name,
        module,
        observations_cls=observations_cls,
        actions_cls=actions_cls,
        rewards_cls=rewards_cls,
        terminations_cls=terminations_cls,
        events_cls=events_cls,
    )
    extra_env_attrs = dict(env_attrs or {})
    final_success_name = _success_term_name(phase_cfgs[-1], final_success)
    extra_env_attrs["evaluation_success"] = getattr(
        terminations_cls(), final_success_name
    )
    extra_env_attrs["task_flow"] = flow
    env_cls = _make_env_cfg(
        env_cfg_cls_name,
        env_cfg_module or module,
        mdp_cls=mdp_cls,
        phase_cfgs=phase_cfgs,
        scene_override=scene_override,
        extra_attrs=extra_env_attrs,
    )
    task_spec = TaskSpec(
        task_id=str(task_id),
        entry_point=entry_point,
        isaaclab_kwargs={"env_cfg_entry_point": env_cfg_entry_point},
        task_flow_entry_point=task_flow_entry_point,
        requires_cameras=requires_cameras,
        reset_randomization_events=tuple(reset_randomization_events),
    )
    definition = CombinedTaskDefinition(
        task_spec=task_spec,
        task_flow=flow,
        env_cfg_cls=env_cls,
        mdp_cfg_cls=mdp_cls,
        actions_cfg_cls=actions_cls,
        terminations_cfg_cls=terminations_cls,
    )
    setattr(env_cls, "task_flow", flow)
    setattr(env_cls, "_combined_task_definition", definition)
    return definition


def _resolve_phase_task(item: str | PhaseTask) -> PhaseTask:
    if isinstance(item, PhaseTask):
        return item
    task_id = str(item)
    return PhaseTask(name=_phase_name_from_task_id(task_id), task_id=task_id)


def _phase_name_from_task_id(task_id: str) -> str:
    suffix = str(task_id).removesuffix("-v0").rsplit("-", maxsplit=1)[-1]
    name = suffix.strip().lower()
    if not name:
        raise ValueError(f"Cannot infer phase name from task ID {task_id!r}.")
    return name


def _phase_env_cfg(task_id: str) -> Any:
    from ioailab.tasks import task_entry_for_task_id

    entry = task_entry_for_task_id(task_id)
    cfg_cls = _load_entry_point(entry.env_cfg_entry_point)
    return cfg_cls()


def _load_entry_point(entry_point: str) -> Any:
    from importlib import import_module

    module_name, _, object_name = str(entry_point).partition(":")
    if not module_name or not object_name:
        raise ValueError(f"Entry point must use 'module:object', got {entry_point!r}.")
    obj: Any = import_module(module_name)
    for attr in object_name.split("."):
        obj = getattr(obj, attr)
    return obj


def _success_term(cfg: Any, task_id: str) -> DoneTerm:
    term = getattr(cfg, "evaluation_success", None)
    if term is None or not hasattr(term, "func"):
        raise ValueError(
            f"Phase task {task_id!r} must define EnvCfg.evaluation_success."
        )
    return term


def _success_func(term: DoneTerm) -> Callable[[Any], Any]:
    def _predicate(env: Any) -> Any:
        return _call_term(term, env)

    _predicate.__name__ = getattr(term.func, "__name__", "phase_success")
    return _predicate


def _call_term(term: DoneTerm, env: Any) -> Any:
    return term.func(env, **dict(getattr(term, "params", {}) or {}))


def _default_phase_agent(task_id: str) -> Callable[[Any], Any]:
    def _agent(env: Any) -> Any:
        try:
            return nav_agent_for_task(task_id)
        except ValueError:
            from ioailab.agents import CuroboPlannerAgent

            motion_plan_for_task(task_id)
            task_options = getattr(env, "task_options", {})
            if task_options:
                return CuroboPlannerAgent.from_task(
                    task_id, task_options=dict(task_options)
                )
            return CuroboPlannerAgent.from_task(task_id)

    return _agent


def _infer_action_terms(actions_cfg: Any) -> tuple[str, ...]:
    terms: list[str] = []
    for attr in _public_cfg_fields(actions_cfg):
        value = getattr(actions_cfg, attr)
        if value is None or callable(value):
            continue
        terms.append(_action_term_name(attr))
    return tuple(terms)


def _action_term_name(attr: str) -> str:
    if attr.startswith("base"):
        return "base"
    if attr.startswith("arm"):
        return "left_arm"
    if attr.startswith("gripper"):
        return "left_gripper"
    return attr.removesuffix("_action")


def _make_actions_cfg(name: str, module: str, phase_cfgs: Sequence[Any]) -> type:
    attrs: dict[str, Any] = {"__module__": module}
    for cfg in phase_cfgs:
        for attr in _public_cfg_fields(cfg.actions):
            value = getattr(cfg.actions, attr)
            if value is None or callable(value) or attr in attrs:
                continue
            attrs[attr] = value
    return configclass(type(name, (), attrs))


def _make_terminations_cfg(
    name: str,
    module: str,
    *,
    specs: Sequence[PhaseTask],
    phase_cfgs: Sequence[Any],
    final_success: DoneTerm,
) -> type:
    final_phase_name = specs[-1].name
    final_success_name = _success_term_name(phase_cfgs[-1], final_success)
    attrs: dict[str, Any] = {
        "__module__": module,
        "time_out": DoneTerm(func=base_mdp.time_out, time_out=True),
        final_success_name: DoneTerm(
            func=env_flow.phase_gated_success(final_phase_name, final_success),
        ),
    }
    for spec, cfg in zip(specs, phase_cfgs, strict=True):
        success = _success_term(cfg, spec.task_id)
        for attr in _public_cfg_fields(cfg.terminations):
            if attr == "time_out" or attr in attrs:
                continue
            term = getattr(cfg.terminations, attr)
            if not _is_done_term(term) or _same_done_term(term, success):
                continue
            attrs[f"{spec.name}_{attr}"] = DoneTerm(
                func=env_flow.phase_gated_success(spec.name, term),
                time_out=bool(getattr(term, "time_out", False)),
            )
    return configclass(type(name, (), attrs))


def _make_mdp_cfg(
    name: str,
    module: str,
    *,
    observations_cls: type,
    actions_cls: type,
    rewards_cls: type,
    terminations_cls: type,
    events_cls: type,
) -> type:
    attrs = {
        "__module__": module,
        "__annotations__": {
            "observations": observations_cls,
            "actions": actions_cls,
            "rewards": rewards_cls,
            "terminations": terminations_cls,
            "events": events_cls,
        },
        "observations": observations_cls(),
        "actions": actions_cls(),
        "rewards": rewards_cls(),
        "terminations": terminations_cls(),
        "events": events_cls(),
        "commands": None,
        "curriculum": None,
    }
    return configclass(type(name, (), attrs))


def _make_env_cfg(
    name: str,
    module: str,
    *,
    mdp_cls: type,
    phase_cfgs: Sequence[Any],
    scene_override: Any | None,
    extra_attrs: dict[str, Any],
) -> type:
    from ioailab.tasks.common.defaults import DefaultEnvCfg

    attrs = {"__module__": module}
    for cfg in phase_cfgs:
        for attr in _public_env_attrs(cfg):
            attrs.setdefault(attr, getattr(cfg, attr))
    attrs.update(extra_attrs)
    if scene_override is not None:
        attrs["scene"] = scene_override
    return configclass(type(name, (mdp_cls, DefaultEnvCfg), attrs))


def _make_observations_cfg(name: str, module: str, phase_cfgs: Sequence[Any]) -> type:
    first = type(phase_cfgs[0].observations)
    if all(type(cfg.observations) is first for cfg in phase_cfgs):
        return first
    attrs: dict[str, Any] = {"__module__": module, "__annotations__": {}}
    group_names: list[str] = []
    for cfg in phase_cfgs:
        for group_name in _public_cfg_fields(cfg.observations):
            value = getattr(cfg.observations, group_name)
            if value is None or callable(value):
                continue
            if group_name not in group_names:
                group_names.append(group_name)
    for group_name in group_names:
        groups = tuple(
            getattr(cfg.observations, group_name)
            for cfg in phase_cfgs
            if hasattr(cfg.observations, group_name)
        )
        group_cls = _make_observation_group_cfg(
            f"{name}{_camel_name(group_name)}",
            module,
            groups,
        )
        attrs["__annotations__"][group_name] = group_cls
        attrs[group_name] = group_cls()
    return configclass(type(name, (), attrs))


def _make_observation_group_cfg(name: str, module: str, groups: Sequence[Any]) -> type:
    first = type(groups[0])
    if all(type(group) is first for group in groups):
        return first
    attrs: dict[str, Any] = {"__module__": module}
    for group in groups:
        for attr in _public_cfg_fields(group):
            value = getattr(group, attr)
            if value is None or callable(value) or attr in attrs:
                continue
            attrs[attr] = value

    concatenate_terms = all(
        bool(getattr(group, "concatenate_terms", True)) for group in groups
    )
    enable_corruption = any(
        bool(getattr(group, "enable_corruption", False)) for group in groups
    )

    def __post_init__(self) -> None:
        self.enable_corruption = enable_corruption
        self.concatenate_terms = concatenate_terms

    attrs["__post_init__"] = __post_init__
    return configclass(type(name, (ObsGroup,), attrs))


def _make_events_cfg(name: str, module: str, base_events_cls: type) -> type:
    base_events = base_events_cls()
    attrs: dict[str, Any] = {"__module__": module}
    for attr in _public_cfg_fields(base_events):
        value = getattr(base_events, attr)
        if value is None or callable(value):
            continue
        attrs[attr] = value
    attrs["reset_task_phase"] = EventTerm(func=env_flow.reset_task_phases, mode="reset")
    return configclass(type(name, (), attrs))


def _make_task_flow(
    specs: Sequence[PhaseTask],
    phase_cfgs: Sequence[Any],
    phase_state_getter: str,
) -> TaskFlowSpec:
    return TaskFlowSpec(
        phases=tuple(
            TaskPhaseSpec(
                name=spec.name,
                phase_task_id=spec.task_id,
                success=_success_func(_success_term(cfg, spec.task_id)),
                default_agent=spec.agent or _default_phase_agent(spec.task_id),
                action_terms=spec.action_terms or _infer_action_terms(cfg.actions),
                fixed_base=spec.fixed_base,
            )
            for spec, cfg in zip(specs, phase_cfgs, strict=True)
        ),
        final_phase=specs[-1].name,
        phase_state_getter=phase_state_getter,
    )


def _success_term_name(cfg: Any, success: DoneTerm) -> str:
    terminations = getattr(cfg, "terminations", None)
    if terminations is not None:
        for attr in _public_cfg_fields(terminations):
            term = getattr(terminations, attr)
            if _is_done_term(term) and _same_done_term(term, success):
                return str(attr)
    return "task_success"


def _is_done_term(value: Any) -> bool:
    return hasattr(value, "func") and hasattr(value, "params")


def _same_done_term(left: DoneTerm, right: DoneTerm) -> bool:
    left_params = dict(getattr(left, "params", {}) or {})
    right_params = dict(getattr(right, "params", {}) or {})
    return left.func is right.func and left_params == right_params


def _caller_module_name() -> str:
    return str(sys._getframe(2).f_globals.get("__name__", "__main__"))


def _camel_name(value: str) -> str:
    return "".join(part.capitalize() for part in str(value).split("_"))


def _public_cfg_fields(cfg: Any) -> tuple[str, ...]:
    fields: set[str] = set(getattr(type(cfg), "__annotations__", {}))
    fields.update(
        name
        for name in vars(type(cfg))
        if not name.startswith("_") and name not in {"class_type"}
    )
    return tuple(sorted(fields))


def _public_env_attrs(cfg: Any) -> Iterable[str]:
    for name in (
        "gripper_joint_names",
        "gripper_open_val",
        "gripper_threshold",
        "goal_position",
        "goal_yaw",
        "success_radius",
        "max_command_speed",
        "base_body_name",
        "scene",
        "recorders",
        "evaluation_success",
    ):
        if hasattr(cfg, name):
            yield name


__all__ = [
    "CombinedTaskDefinition",
    "PhaseTask",
    "combined_task",
    "combined_task_definition",
    "combine_tasks",
    "phase",
    "task_sequence",
]
