"""Galbot-specific IsaacLab sensor config factories."""

from ioailab.robots.g1.sensors.core import G1Sensors
from ioailab.robots.g1.sensors.camera import (
    DEFAULT_CAMERA_HEIGHT,
    DEFAULT_CAMERA_UPDATE_PERIOD,
    DEFAULT_CAMERA_WIDTH,
    FRONT_HEAD_CAMERA_PARENT_PRIM_PATH,
    FRONT_HEAD_CAMERA_POS,
    FRONT_HEAD_CAMERA_ROT,
    G1_TORSO_BASE_PRIM_PATH,
    LEFT_WRIST_CAMERA_PARENT_PRIM_PATH,
    LEFT_WRIST_CAMERA_POS,
    LEFT_WRIST_CAMERA_ROT,
    RIGHT_WRIST_CAMERA_PARENT_PRIM_PATH,
    RIGHT_WRIST_CAMERA_POS,
    RIGHT_WRIST_CAMERA_ROT,
    ROBOT_PRIM_PATH,
)

__all__ = [
    "G1Sensors",
    "DEFAULT_CAMERA_HEIGHT",
    "DEFAULT_CAMERA_UPDATE_PERIOD",
    "DEFAULT_CAMERA_WIDTH",
    "FRONT_HEAD_CAMERA_PARENT_PRIM_PATH",
    "FRONT_HEAD_CAMERA_POS",
    "FRONT_HEAD_CAMERA_ROT",
    "G1_TORSO_BASE_PRIM_PATH",
    "LEFT_WRIST_CAMERA_PARENT_PRIM_PATH",
    "LEFT_WRIST_CAMERA_POS",
    "LEFT_WRIST_CAMERA_ROT",
    "RIGHT_WRIST_CAMERA_PARENT_PRIM_PATH",
    "RIGHT_WRIST_CAMERA_POS",
    "RIGHT_WRIST_CAMERA_ROT",
    "ROBOT_PRIM_PATH",
]
